version: '2'
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
