environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
install:
  - set CI=true
  - set PATH=%APPDATA%\npm;c:\MinGW\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
