environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install
test_script:
  - node --version
  - npm --version
  - ps: npm test
build: off
